### PR TITLE
Changes the way sinlge cutter overhang is parsed.

### LINKED ISSUE #184: ValueError(numpy.dtype has the wrong size, try recompiling)
Installed ipyrad via miniconda, as described in the documentation.
However, after filling in the parameters file, I get the following:

```
ipyrad -p params-test1.txt -s 1234567 --preview

 -------------------------------------------------------------
  ipyrad [v.0.3.41]
  Interactive assembly and analysis of RAD-seq data
 -------------------------------------------------------------
  loading Assembly: test1
  from saved path: ~/GBS/ipyrad_0.3.41/test1.json
  New Assembly: test1
  local compute node: [8 cores] on Loki

  Step 1: Demultiplexing fastq data to Samples
    Running preview mode: subselecting maximum of 4000000 reads
  [####################] 100%  chunking large files  | 0:00:00
  [                    ]   0%  sorting reads         | 0:00:00
ValueError(numpy.dtype has the wrong size, try recompiling)
```

This has led me [here](http://stackoverflow.com/questions/17709641/valueerror-numpy-dtype-has-the-wrong-size-try-recompiling#18369312), which boils down to binary incompatibility.
Could there be an issue with setting up the conda environment for running ipyrad?
I'm doing this on an almost out-dated Ubuntu 12.04 server, which may explain why some binary incompatibilities are arising (eg. using system numpy, vs conda pandas).
I'll keep looking for the root cause and a solution to the issue.

### PR DESCRIPTION
**Pull request by StuntsPT**
Before this PR, using ipyrad with GBS data, there was an issue with the overhang string:
"TGCAG" would result in an error;
"TGCAG, TGCAG" would return in a different result from "TGCAG,"

With this PR, all three forms return the same result and "TGCAG" will no longer result in errors.
Furthermore, this fixes #184 
Also, the IDE I've used got rid of all the extra whitespaces that were present a bit all over the changed file. If you do not wish for this to be changed, let me know and I'll make a new PR where this is not altered.

### CODE REVIEW

**Comment by isaacovercast** [comment]
Awesome! Thanks for the PR. Looks like this was affecting ALL datatypes, but only if the filter_adapters param was >= 1, so i made some slight mods to fix it for everyone. Thanks again!

**Comment by StuntsPT** [comment]
You're welcome! Glad I could help.

**Comment by isaacovercast** [comment]
I merged and pushed to master, it'll go out in the next conda release.

**Comment by StuntsPT** [comment]
Awesome!

**Pull request closed without merging**
